name: Build Docker Image

on:
  push:
    branches: [master]

jobs:
  build_push:
    name: Build and Push image to Docker Hub
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_NAME}}:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push image to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_NAME}}:latest
