name: Render video
on:
  workflow_dispatch:
jobs:
  render:
    name: Render video
    runs-on: ubuntu-22.04
    env:
      REMOTION_API_KEY: ${{ secrets.REMOTION_API_KEY }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      RECOVERY_EMAIL: ${{ secrets.RECOVERY_EMAIL }}
      YOUTUBE_CREDENTIALS_KEY: ${{ secrets.YOUTUBE_CREDENTIALS_KEY }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
      - run: npm i
      - run: npm run build
      - run: node upload.js
