name: Render video
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    env:
      REMOTION_API_KEY: ${{ secrets.REMOTION_API_KEY }}
      YOUTUBE_CREDENTIALS_KEY: ${{ secrets.YOUTUBE_CREDENTIALS_KEY }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
      - run: npm i
      - run: npm run build
      - run: npm run upload
